// proyect-ssr-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { FormGroup, FormBuilder, FormsModule, ReactiveFormsModule } from  '@angular/forms';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, FormsModule, ReactiveFormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  
  contactForm: FormGroup;
  constructor(private formBuilder: FormBuilder) {
    this.createContactForm();
  }

  createContactForm(){
    this.contactForm = this.formBuilder.group({
      fullName: [''],  
      email: [''],
      message: ['']
    });
  }

  onSubmit() {
      console.log('Your form data : ', this.contactForm.value );
  }

}

<div class="form">

  <h1> Ejemplo de formulario reactivo </h1>

  <form class="form-content" [formGroup]="contactForm" (ngSubmit)="onSubmit()">

    <div class="form-content-camp">
      <label>Nombre Completo</label>
      <input type="text" name="fullName" placeholder="Eduardo Cardenas" formControlName="fullName">
    </div>

    <div class="form-content-camp">
      <label>Correo Electronico</label>
      <input type="email" name="email" placeholder="Ejemplo@correo.com" formControlName="email">
    </div>

    <div class="form-content-camp">
      <label>Mensaje</label>
      <textarea name="message" placeholder="Necesito más información" formControlName="message"></textarea>
    </div>

    <button>Enviar</button>
  </form>

</div>

<router-outlet></router-outlet>

// proyect-ssr-reactjs/src/App.js
import React from "react";
import { Form, Title, Content, Camp, Button } from './Styles.js';
import { ThemeProvider } from '@emotion/react';
import { theme } from "./theme";

const App = () => {
  return (
    <ThemeProvider theme={theme}>
      <Form className="form">

        <Title> Ejemplo de formulario reactivo </Title>

        <Content className="form-content">

          <Camp className="form-content-camp">
            <label>Nombre Completo</label>
            <input type="text" name="fullName" placeholder="Eduardo Cardenas" />
          </Camp>

          <Camp className="form-content-camp">
            <label>Correo Electronico</label>
            <input type="email" name="email" placeholder="Ejemplo@correo.com" />
          </Camp>

          <Camp className="form-content-camp">
            <label>Mensaje</label>
            <textarea name="message" placeholder="Necesito más información" ></textarea>
          </Camp>

          <Button>Enviar</Button>
        </Content>
      </Form >
    </ThemeProvider>
  );
};

export default App;
